spring:
  application:
    name: SCW-ORDER
  datasource:
    username: root
    password: 123456789gk
    url: jdbc:mysql://192.168.113.129:3306/atcrowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.113.129
    port: 6379


mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-ORDER
    prefer-ip-address: true

server:
  port: 9000

feign:
  hystrix:
    enabled: true



